services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: mtto-dynamodb
    restart: always
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    ports:
      - "8000:8000"
    volumes:
      - dynamodbdata:/home/dynamodblocal/data
    networks:
      - mtto-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mtto-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      DYNAMODB_ENDPOINT: http://dynamodb-local:8000
    volumes:
      - ./backend/src:/app/src
      - ./backend/serverless.yaml:/app/serverless.yaml
    depends_on:
      - dynamodb-local
    networks:
      - mtto-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mtto-frontend
    restart: always
    ports:
      - "8080:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - mtto-network

volumes:
  dynamodbdata:

networks:
  mtto-network:
    driver: bridge
