extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  eqeqeq: [ "error", "always" ]
  no-await-in-loop: 0
  no-restricted-syntax: 0
  no-plusplus: 0
  arrow-parens: [ "error", "always" ]
  no-return-await: "error"
  arrow-body-style: [
    "error",
    "as-needed",
    {
      "requireReturnForObjectLiteral": true
    }
  ]
  object-curly-spacing: [ 'error', 'always' ]
  quotes: [ 2, 'single', { avoidEscape: true }]
  no-underscore-dangle: 0
  linebreak-style: [ "error", "windows" ]
  comma-dangle: ["error", { "functions": "never" }]
  no-mixed-spaces-and-tabs: [ "error", "smart-tabs" ]
  object-shorthand: [
    "error",
    "always",
    {
      "avoidExplicitReturnArrows": true,
      "ignoreConstructors": true
    }
  ]
  max-len: [ "error", { "code": 180 } ]
  indent: ["error", 2]
  no-use-before-define: [ "error", { "functions": false } ]
  no-param-reassign: [ "error", { "props": false } ]
  no-console: "error"
  no-dupe-args: "error"
  no-multiple-empty-lines: [
    "error",
    {
      "max": 1,
      "maxBOF": 0,
      "maxEOF": 0
    }
  ]
